### ISSUE TITLE
(git.install) Parameter to disable explorer integration

### ISSUE THREAD

**Issue by iTob191** [ferventcoder/chocolatey-packages#197] opened 2016-11-04 13:09 UTC
http://disq.us/p/16kufgd

I'd really like to have a parameter to disable explorer integration.

**Comment by ferventcoder** [comment] 2016-11-07 16:29
We used to have it that way. Agreed a parameter to allow someone to choose to change the default would be great!

**Comment by bazzilic** [comment] 2016-11-08 04:59
@ferventcoder I made a PR #169 that introduces that parameter two months ago, was hoping you would merge it.

**Comment by iTob191** [comment] 2016-11-13 18:26
How about something like this: https://github.com/iTob191/chocolatey-packages/commit/7cdc7cc98cda3e1f909ddd118d38b00c3c0f0d94 ?
That way there is no need for any regexp magic to remove the components again.

**Comment by bazzilic** [comment] 2016-11-13 18:29
It's not magic :)
But I'd be happy with anything that allows to disable shell integration, be it your PR or mine.

**Comment by iTob191** [comment] 2016-11-18 23:25
So @ferventcoder needs to decide on one^^

**Comment by ferventcoder** [comment] 2016-11-23 20:38
@iTob191 was there a PR associated with your commits?

**Comment by iTob191** [comment] 2016-11-26 21:25
Not yet. The commit was only a draft that I haven't tested yet.

**Comment by bazzilic** [comment] 2016-11-27 03:05
@ferventcoder there is a PR waiting that adds that parameter to the package: #169

**Comment by ferventcoder** [comment] 2016-11-28 06:45
Yes. I did like what @iTob191 proposed. It cleans up other logic in the package and is much easier to reason about.

I'm all for simpler logic, and so are package consumers who may not be strong in PowerShell.

**Comment by ferventcoder** [comment] 2016-11-28 06:57
This is a duplicate of #151?

**Comment by bazzilic** [comment] 2016-11-28 08:21
Yes, it is.

**Comment by majkinetor** [comment] 2016-12-23 11:57
Both issues can be closed.

**Closed** 2016-12-29 13:27 UTC
Labels: enhancement
